#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright Â© 2016-2025 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

server:
  # Server bind address
  address: "HTTP_BIND_ADDRESS"
  # Server bind port
  port: "HTTP_BIND_PORT"
browser:
  # Browser launch timeout (ms)
  launchTimeout: "BROWSER_LAUNCH_TIMEOUT"
  # Default page navigation timeout (ms)
  defaultPageNavigationTimeout: "DEFAULT_PAGE_NAVIGATION_TIMEOUT"
  # Generate report request timeout (ms)
  generateReportTimeout: "GENERATE_REPORT_TIMEOUT"
  # Load dashboard resources timeout (ms)
  loadDashboardResourcesTimeout: "LOAD_DASHBOARD_RESOURCES_TIMEOUT"
  # Dashboard idle wait time (ms)
  dashboardIdleWaitTime: "DASHBOARD_IDLE_WAIT_TIME"
  # Max browser pages
  maxPages: "BROWSER_MAX_PAGES"
  # This parameter determines whether to create a new page for each web report.
  # When set to 'true', each web report will open on a separate page, providing clear separation and convenient viewing of reports.
  #
  # Caution:
  # - If this parameter is enabled ('true'), data caching functionality will be disabled.
  #   This means that data for each report will be reloaded every time the report is opened,
  #   which may increase page load times and server load.
  # - When this parameter is disabled ('false'), all web reports will open on a single page,
  #   allowing caching to be used for improved performance and faster page loading.
  useNewPage: "USE_NEW_PAGE_FOR_REPORT"
logger:
  # Sets the logging level.
  # Available levels and their priorities:
  # { error: 0, warn: 1, info: 2, http: 3, verbose: 4, debug: 5, silly: 6 }
  level: "LOGGER_LEVEL"
  path: "LOG_FOLDER"
  filename: "LOGGER_FILENAME"
