#
# Copyright Â© 2016-2023 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.0'

services:
  postgres:
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
  tb-monolith:
    volumes:
      - tb-log-volume:/var/log/thingsboard
  tb-edge:
    volumes:
      - tb-edge-log-volume:/var/log/tb-edge
      - tb-edge-data-volume:/data
volumes:
  postgres-db-volume:
    external:
      name: ${POSTGRES_DATA_VOLUME}
  tb-log-volume:
    external:
      name: ${TB_LOG_VOLUME}
  tb-edge-log-volume:
    external:
      name: ${TB_EDGE_LOG_VOLUME}
  tb-edge-data-volume:
    external:
      name: ${TB_EDGE_DATA_VOLUME}
